version: '2'

services:
    php:
        volumes:
            - ./:/app
        environment:
            SYMFONY_ENV: dev
            SYMFONY_DEBUG: 1
        user: '1000:1000'
        ports:
            - '8080:8080'


